#ifndef GUARD_CONSTANTS_FLAGS_H
#define GUARD_CONSTANTS_FLAGS_H

#define SYSTEM_FLAGS 0x800

#define FLAG_SYS_POKEDEX_GET      (SYSTEM_FLAGS + 0x01)
#define FLAG_SYS_GAME_CLEAR       (SYSTEM_FLAGS + 0x04)
#define FLAG_SYS_NATIONAL_DEX     (SYSTEM_FLAGS + 0x36)
#define FLAG_SYS_RIBBON_GET       (SYSTEM_FLAGS + 0x3B)
#define FLAG_SYS_EXDATA_ENABLE    (SYSTEM_FLAGS + 0x4C)

#endif // GUARD_CONSTANTS_FLAGS_H
