#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_CHERI_BERRY 133
#define ITEM_ENIGMA_BERRY 175

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX  ITEM_ENIGMA_BERRY

#define ITEMS_COUNT 349

#define ITEM_TO_BERRY(itemId)(((itemId) - FIRST_BERRY_INDEX) + 1)

#endif // GUARD_CONSTANTS_BERRY_H
